/*
*User Constants
*
*/

 export const USER_LIST_REQUEST = 'app/User/USER_LIST_REQUEST';
 export const USER_LIST_REQUEST_SUCCESS = 'app/User/USER_LIST_REQUEST_SUCCESS';
 export const USER_LIST_REQUEST_FAIL = 'app/User/USER_LIST_REQUEST_FAIL';
 export const GET_USER_DETAILS_REQUEST = 'app/User/GET_USER_DETAILS_REQUEST';
 export const GET_USER_DETAILS_REQUEST_SUCCESS = 'app/User/GET_USER_DETAILS_REQUEST_SUCCESS';
 export const GET_USER_DETAILS_REQUEST_FAIL = 'app/User/GET_USER_DETAILS_REQUEST_FAIL';
